version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kS812Nc712bXCl92
      POSTGRES_USER: timeit_dev
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - '6080:8080'
