---
- hosts: timeit_hosts
  name: "Recreate Postgres Containers"
  vars: { }
  vars_files:
    - common_variables.yml
  tasks:
    - name: Create postgres volume
      docker_volume:
        state: present
        name: "{{ postgres_data_volume }}"
    - name: Start postgres container
      docker_container:
        state: started
        name: "{{ postgres_container }}"
        image: postgres
        volumes:
          - "{{ postgres_data_volume }}:/var/lib/postgresql/data"
        ports:
          - "{{ database_port }}:5432"
        restart_policy: unless-stopped
        env_file: "{{ postgres_env }}"
