---
- hosts: timeit_hosts
  name: "Restart Frontend Containers"
  vars:
    app_name: timeit-frontend
  vars_files:
    - common_variables.yml
  tasks:
    - name: Stop frontend container
      docker_container:
        state: absent
        name: "{{ app_name }}"
    - name: Start frontend container
      docker_container:
        state: started
        recreate: yes
        name: "{{ app_name }}"
        image: "{{ app_name }}"
        ports:
          - "{{ frontend_port }}:80"
        restart_policy: unless-stopped
