---
- hosts: timeit_hosts
  name: "Frontend Deployment"
  vars:
    app_name: timeit-frontend
    app_image: "{{ app_name }}.tar"
    frontend_path: "../packages/frontend"
    frontend_dockerfile: "{{ frontend_path }}/Dockerfile"
  vars_files:
    - common_variables.yml
  tasks:
    - name: Build frontend image
      delegate_to: localhost
      command: "docker build -t {{ app_name }} -f {{ frontend_dockerfile }} .."
    - name: Save frontend image
      delegate_to: localhost
      command: "docker save --output {{ app_image }} {{ app_name }}"
    - name: Copy app image to the target
      become: yes
      copy:
        src: "{{ app_image }}"
        dest: "{{ deploy_dir }}/{{ app_image }}"
    - name: Delete local image tar
      delegate_to: localhost
      file:
        state: absent
        path: "{{ app_image }}"
    - name: Load app image
      become: yes
      command: "docker load --input {{ deploy_dir }}/{{ app_image }}"
    - name: Delete app image tar from the target
      become: yes
      file:
        state: absent
        path: "{{ deploy_dir }}/{{ app_image }}"

- import_playbook: create_frontend.yml
