/**
 * Errors used in the API responses
 */

export const INVALID_TOKEN_ERROR: string = 'INVALID_TOKEN';

export const INACTIVE_ACCOUNT_ERROR: string = 'INACTIVE_ACCOUNT';

export const DISABLED_ACCOUNT_ERROR: string = 'DISABLED_ACCOUNT';

export const INVALID_CREDENTIALS_ERROR: string = 'INVALID_CREDENTIALS';

export const INACTIVE_TOKEN_ERROR: string = 'INACTIVE_TOKEN';

export const NO_ACCESS_TOKEN_ERROR: string = 'NO_ACCESS_TOKEN';

export const UNKNOWN_SERVER_ERROR: string = 'UNKNOWN_SERVER';

export const RESOURCE_NOT_FOUND_ERROR: string = 'RESOURCE_NOT_FOUND';

export const SESSION_ENDED_ERROR: string = 'SESSION_ENDED';

export const ACCOUNT_NOT_FOUND_ERROR: string = 'ACCOUNT_NOT_FOUND';

export const INSUFFICIENT_PRIVILEGES_ERROR: string = 'INSUFFICIENT_PRIVILEGES';

export const ACCOUNT_ALREADY_EXISTS_ERROR: string = 'ACCOUNT_ALREADY_EXISTS';

export const ALREADY_PROJECT_MEMBER_ERROR: string = 'ALREADY_PROJECT_MEMBER';

export const MAIL_TOKEN_NOT_FOUND_ERROR: string = 'MAIL_TOKEN_NOT_FOUND';

export const INCORRECT_MAIL_TOKEN_ERROR: string = 'INCORRECT_MAIL_TOKEN';

export const EXPIRED_MAIL_TOKEN_ERROR: string = 'EXPIRED_MAIL_TOKEN';

export const ALREADY_REQUESTED_MAIL_TOKEN_ERROR: string =
  'ALREADY_REQUESTED_MAIL_TOKEN';

export const COULD_NOT_SEND_EMAIL_ERROR: string = 'COULD_NOT_SEND_EMAIL';
