name: Build Images and Deploy to Personal Registry

on:
  push:
    branches: [master]

concurrency:
  group: build-images
  cancel-in-progress: true

env:
  REGISTRY: registry.jamezrin.name

jobs:
  build-packages:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: true
      matrix:
        platform: ['amd64', 'arm64']
        package: ['frontend', 'backend']
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Login to my Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Create docker context
        run: docker context create builders
      - uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          endpoint: builders
      - name: Get package version
        id: build_version
        run: |
          version=$(jq -r .version ./packages/${{ matrix.package }}/package.json)
          echo "::set-output name=version::$version"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./packages/${{ matrix.package }}/Dockerfile
          tags: ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:${{ steps.build_version.outputs.version }}-${{ matrix.platform }}

  create-manifest:
    needs: [build-packages]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: ['frontend', 'backend']
    steps:
      - uses: actions/checkout@v2
      - name: Login to my Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Get package version
        id: build_version
        run: |
          version=$(jq -r .version ./packages/${{ matrix.package }}/package.json)
          echo "::set-output name=version::$version"
      - name: Create versioned manifest
        run: |
          docker manifest create ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:${{ steps.build_version.outputs.version }} \
            --amend ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:${{ steps.build_version.outputs.version }}-arm64 \
            --amend ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:${{ steps.build_version.outputs.version }}-amd64

          docker manifest push ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:${{ steps.build_version.outputs.version }}
      - name: Create latest manifest 
        run: |
          docker manifest create ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:latest \
            --amend ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:${{ steps.build_version.outputs.version }}-arm64 \
            --amend ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:${{ steps.build_version.outputs.version }}-amd64

          docker manifest push ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:latest
