name: Build Images and Deploy to Personal Registry

on:
  push:
    branches: [master]

env:
  REGISTRY: registry.jamezrin.name

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to my Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: (frontend) Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./packages/frontend/Dockerfile
          tags: ${{ env.REGISTRY }}/timeit-webapp/timeit-frontend:latest
      - name: (backend) Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./packages/backend/Dockerfile
          tags: ${{ env.REGISTRY }}/timeit-webapp/timeit-backend:latest
