name: Build Images and Deploy to Personal Registry

on:
  push:
    branches: [master]

concurrency:
  group: build-images
  cancel-in-progress: true

env:
  REGISTRY: registry.jamezrin.name

jobs:
  build-packages:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: true
      matrix:
        platform: ['amd64', 'arm64']
        package: ['frontend', 'backend']
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Create docker context
        id: buildx-create-context
        run: docker context create builders
      - uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          endpoint: builders
      - name: Login to my Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.platform }}
          file: ./packages/${{ matrix.package }}/Dockerfile
          tags: ${{ env.REGISTRY }}/timeit-webapp/timeit-${{ matrix.package }}:latest
