name: update-shrinkwrap-and-test

on:
  push: {}

env:
  BROWSERSLIST_IGNORE_OLD_DATA: "1"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install rush and pnpm
        run: npm install -g @microsoft/rush pnpm
      - name: Install dependencies with shrinkwrap update
        run: rush update
      - name: Commit and push updated shrinkwrap
        continue-on-error: true
        if: ${{ !startsWith(github.ref_name, 'renovate/') }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          REMOTE_HTTPS_URL="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"

          git add common/config/rush/pnpm-lock.yaml
          git commit -m "Update pnpm lockfile"

          git remote set-url --push origin $REMOTE_HTTPS_URL
          git push -u origin $GITHUB_REF
      - name: Rebuild all projects
        run: rush rebuild
